FROM python:3.7-alpine
COPY requirements.txt .
COPY app.py .
ENV FLASK_APP=app
ENV FLASK_DEBUG=development
WORKDIR .
RUN pip install -r requirements.txt
EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app "]
