FROM python:3.7-alpine
RUN apk update && apk add --no-cache bash
RUN apk add --update build-base python3-dev py-pip
COPY requirements.txt .
COPY app.py .
ENV LIBRARY_PATH = /lib:/usr/lib
ENV FLASK_APP=app
ENV FLASK_DEBUG=development
WORKDIR .
RUN pip install -r requirements.txt
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["app.py"]