version: '3'
services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    restart: always
  flask:
    build:
      context: .
      dockerfile: Dockerfile.python2
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: always
    volumes:
        - /home/ubuntu/.aws/credentials:/root/.aws/credentials

