FROM ubuntu:20.04
MAINTAINER GEUMSEONG YANG  <sahayanayang@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get update
RUN apt-get install -y python3.7


WORKDIR /app
COPY requirements.txt /app

ENTRYPOINT ["python"]
