version: '3'
services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    restart: always
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    depends_on:
      - redis
    restart: always

